excluded:
  - ./Pods

disabled_rules:
  - variable_name
  - type_name
  - implicit_getter
  - void_return
  - closure_parameter_position
  - trailing_whitespace

opt_in_rules:
- conditional_returns_on_newline
- let_var_whitespace
- literal_expression_end_indentation
- number_separator
- operator_usage_whitespace
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- switch_case_on_newline
- vertical_parameter_alignment_on_call
- unneeded_parentheses_in_closure_argument
- closure_spacing
- closure_end_indentation
- multiline_arguments

line_length:
  - 180

function_body_length:
  - 200

large_tuple:
  - 4
